### ISSUE TITLE
SoftException error

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursInstaller#11]
@damirius what does this mean? Permissions are not set properly? Did you run into this problem to install vs, qas and raw-labels deploys?

```
[Tue Aug 09 02:35:21.231781 2016] [:error] [pid 26029:tid 140056685680384] [client 81.252.62.180:59417] SoftException in Application.cpp:255: File "/home/puzzlout/public_html/code-review/api/web/app.php" is writeable by group
[Tue Aug 09 02:35:21.231863 2016] [core:error] [pid 26029:tid 140056685680384] [client 81.252.62.180:59417] End of script output before headers: app.php

```

**Comment by WebDevJL** [comment]
@damirius 

Found the solution: `chmod -R 755 /home/puzzlout/public_html/codereview/`

**Comment by damirius** [comment]
@WebDevJL 

I've added some stuff to fix that on the end of installer, well almost the same line you wrote there. Here is the commit https://github.com/Puzzlout/TrekToursInstaller/commit/eb6a6f0409cc71df39e1db420269dde9dc9952f7
You deployed new instance of the app in codereview? Don't know why that line isn't run, you should be prompted for root password and then chmod should be recursively run on selected directory.
Since we run first-install.sh like this `bash lw/first-install.sh vs` from vs directory logged in as puzzlout user. Where vs is the directory we want to install both app and api. For example you can run it also like this `bash lw/first-install.sh tt-raw-labels` to install it in tt-raw-labels directory or `bash lw/first-install.sh trektours` to install it in trektours directory and so on.

In few hours I'll sit down and see what else can be done to streamline the process of deployment as much as we can. For example since we already need to run `first-install.sh` script from directory we want to install it to, maybe we can go without an argument and instead somehow fetch the current directory in script and run it with that. There are maybe some other tweaks we could do also.

**Comment by WebDevJL** [comment]
@damirius I ran `bash codereview/global/first-install.sh codereview` from
inside the public_html folder. Maybe I didn't copy the chmod line...

I let you look at the improvements. If possible, I'd like to able to
install and reinstall in seconds (it takes 1 minute on LiquidWeb!). My
global folder work seamlessly on local macintosh and LiquidWeb. Maybe we
can clean up the lw and local-unix folders soon.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

Well in seconds is quite hard. Mostly it takes time to update/install bower and composer packages. Composer takes time, it's great that we use liquidweb now, it's a lot faster there. But composer always uses some time to check and update all packages.

**Comment by WebDevJL** [comment]
@damirius yes, I don't mean to speed up even more the installation/update of application. In fact, I think we are just fine right in time spent to perform an update.

For now, we will keep LiquidWeb. But I am still looking into other options since the client would like to pay in Euros and have invoices for the hosting.
