### ISSUE TITLE
Install version 1.0.2 on LiquidWeb

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursInstaller#9]
@damirius when you are ready.

**Comment by WebDevJL** [comment]
@damirius 

Reminder:
- install 1.0.2-RC1 on QAS deploy
- install 1.0.2 on VS and raw labels deploys

I see that QAS has 1.0.1-RC1 instead of 1.0.1. The RC tags are for VS and raw labels only.

I will update the deploy procedure.

**Comment by damirius** [comment]
@WebDevJL 

I have only releasesd 1.0.2-RC1 on codereview, I haven't pulled anything else on other servers.

**Comment by WebDevJL** [comment]
@damirius One thing about 1.0.2-RC1: when I check the "receive copy" on contact form, I don't receive a copy nor received a email notification on contact@puzzlout.com.

Maybe I installed the email account incorrectly. Can you check? Thanks.

**Comment by damirius** [comment]
@WebDevJL 

Password wasn't set, I fixed that, but we have some bigger problem now. SSL certificate isn't working and we need it for our smtp connection, so I'm looking into this for some time now. I tried downloading new certificate but to no avail, I'll see what else we can do.

**Comment by WebDevJL** [comment]
@damirius where is the SSL certificate? As far as I know we don't have
HTTPS... Is it something missing on the stmp host mail.supremecluster.com?

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

We don't use SSL currently, but mail server does and php has to have CA files to verify them. To be honest I have no idea what's happening since mail worked few days ago when we fixed that outgoing port firewalls. I haven't touched anything regarding server configs since then.
I don't think anything is missing on mail.supremecluster.com since I still can send mails through my local thunderbird client over ssl.

**Comment by WebDevJL** [comment]
@damirius Use the support. Maybe they will help. Maybe the firewall blocked
the outgoing emails because of my testing?

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

They will probably ask me again for root shell access. They told me I can set up root password for them (supports) to see, but since I am secondary user I can't do that. If you are away currently I'll give them pass in the message. But it would be great if we can set it there so they can easily access it if needed.

**Comment by WebDevJL** [comment]
@damirius ask them how to do that and I shall do it.
But are you talking about the root password for ssh access or to
manage.liquidweb.com ?

On 10 Aug 2016 16:43, "damirius" notifications@github.com wrote:

@WebDevJL https://github.com/WebDevJL

They will probably ask me again for root shell access. They told me I can
set up root password for them (supports) to see, but since I am secondary
user I can't do that. If you are away currently I'll give them pass in the
message. But it would be great if we can set it there so they can easily
access it if needed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/Puzzlout/TrekToursInstaller/issues/9#issuecomment-238888969,
or mute the thread

**Comment by WebDevJL** [comment]
@damirius I did that. Closing...
